name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the application
        run: |
          uvicorn app.main:app --port 7751 &

      - name: Run integraion tests
        run: |
          pytest test/

      - name: Stop the application
        run: |
          pkill -f "uvicorn app.main:app"
